# Cargo configuration for cross-platform compatibility
[build]
# Use native target (auto-detect)
# target = "x86_64-unknown-linux-gnu"  # Uncomment for Linux development

# Windows-specific configuration (only used when building for Windows)
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

# Linux-specific configuration
[target.x86_64-unknown-linux-gnu]
rustflags = []

# Platform-specific environment overrides
# Uncomment the appropriate section based on your development platform

# [env]  # Uncomment for Windows development
# CC = "cl.exe"
# CXX = "cl.exe"
# AR = "lib.exe"
# CARGO_TARGET_X86_64_PC_WINDOWS_MSVC_LINKER = "link.exe"
